### PR TITLE
Update webhook processor

### PR DESCRIPTION
**Pull request by estepan**
Add sync webhook handling

### CODE REVIEW

**Comment by tardate** [comment]
@estepan thanks for this. That sync hook definition is untidily non-standard...whatever!
Merging now..

**Comment by estepan** [comment]
@tardate thank you!

**Comment by tardate** [comment]
@estepan np! btw, if possible, it would be great if you could contribute some (real) "sample" payloads - just send them in another P/R if you can (redacted as you wish). 

The existing files in spec/fixtures/webhook_examples/sync_blacklist.json,sync_whitelist.json are ones I just "made up" based on the API docs. But shouldn't really assume the API docs are 100% correct.

**Comment by estepan** [comment]
@tardate np. As soon as I get this feature tested in my staging env.

**Pull request merged**
