### PR TITLE
Fix/handler methods detection

### PR DESCRIPTION
**Pull request by PikachuEXE**
I got a controller that handles event, and it does not handle anything since I defined the methods as `private`
But defining non-action method in controller is bad, thus this PR.

### CODE REVIEW

**Comment by PikachuEXE** [comment]
Hi, does anyone have time to review this PR?
Thanks!

**Comment by tardate** [comment]
Thanks @PikachuEXE ... will do. Sorry, overlooked these P/Rs sitting in the queue

**Comment by PikachuEXE** [comment]
no problem :)
I got more PR to review for my projects :P (public and private)

**Comment by PikachuEXE** [comment]
One month has passed :P

**Comment by tardate** [comment]
consider me suitably flogged;-)
thanks for the fix - perfect!
I've rolled & released this in 1.1.0

**Comment by PikachuEXE** [comment]
Great ;)

**Pull request merged**
